env:
    LOAD-TEST: scripts/load-test/load-test.js
    SMOKE-TEST: scripts/smoke-test/smoke-test.js

name: K6-Automation

on:
    push:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Check pipeline
              uses: actions/checkout@v3

            - name: Run Smoke Test
              uses: grafana/k6-action@v0.2.0
              with:
                cloud: false
                filename: ${{ env.SMOKE-TEST }}

            - name: Run Load Test
              uses: grafana/k6-action@v0.2.0
              with:
                cloud: false
                filename: ${{ env.SMOKE-TEST }}


            - name: Completed
              run: echo "Completed"
